// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using car_booking.Persistence;

#nullable disable

namespace carbooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411195422_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("car_booking.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Liters")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Spaces")
                        .HasColumnType("integer");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Базовая комплектация с механической КПП, кондиционер, ABS",
                            Image = "https://carso.ru/uploads/stock_cars/168/1477/images/chevrolet_aveo_sedan_6.png",
                            Liters = 45,
                            Name = "Chevrolet Aveo LS MT",
                            Price = 1050000m,
                            Spaces = 5,
                            Transmission = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Автоматическая коробка, климат-контроль, мультимедиа",
                            Image = "https://carso.ru/uploads/stock_cars/168/1477/images/chevrolet_aveo_sedan_6.png",
                            Liters = 45,
                            Name = "Chevrolet Aveo LT AT",
                            Price = 1250000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Топовая версия с кожаным салоном и системой безопасности",
                            Image = "https://carso.ru/uploads/stock_cars/168/1477/images/chevrolet_aveo_sedan_6.png",
                            Liters = 45,
                            Name = "Chevrolet Aveo Premier",
                            Price = 1450000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Классический внедорожник с полным приводом",
                            Image = "https://kazan.masmotors.ru/colors/chevrolet-niva/3.png",
                            Liters = 58,
                            Name = "Chevrolet Niva 1.7 MT",
                            Price = 1222000m,
                            Spaces = 5,
                            Transmission = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Городская версия с улучшенным комфортом",
                            Image = "https://kazan.masmotors.ru/colors/chevrolet-niva/3.png",
                            Liters = 58,
                            Name = "Chevrolet Niva Urban",
                            Price = 1350000m,
                            Spaces = 5,
                            Transmission = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Специальная серия с дополнительной защитой",
                            Image = "https://kazan.masmotors.ru/colors/chevrolet-niva/3.png",
                            Liters = 58,
                            Name = "Chevrolet Niva Legend",
                            Price = 1450000m,
                            Spaces = 5,
                            Transmission = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Базовый седан с механической КПП",
                            Image = "https://kazan.masmotors.ru/colors/chevrolet-cruze-sedan/4.png",
                            Liters = 52,
                            Name = "Chevrolet Cruze LS",
                            Price = 1500000m,
                            Spaces = 5,
                            Transmission = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Автоматическая коробка, премиум-комплектация",
                            Image = "https://kazan.masmotors.ru/colors/chevrolet-cruze-sedan/4.png",
                            Liters = 52,
                            Name = "Chevrolet Cruze LTZ",
                            Price = 1800000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Топовая версия с полным пакетом опций",
                            Image = "https://kazan.masmotors.ru/colors/chevrolet-cruze-sedan/4.png",
                            Liters = 52,
                            Name = "Chevrolet Cruze Premier",
                            Price = 2100000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Базовый полноразмерный внедорожник",
                            Image = "https://wallpapers.com/images/hd/white-chevrolet-tahoe-s-u-v-profile-hxxci41yvgrn2kxs.jpg",
                            Liters = 98,
                            Name = "Chevrolet Tahoe LS",
                            Price = 6500000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Люксовая версия с расширенным оснащением",
                            Image = "https://wallpapers.com/images/hd/white-chevrolet-tahoe-s-u-v-profile-hxxci41yvgrn2kxs.jpg",
                            Liters = 98,
                            Name = "Chevrolet Tahoe LTZ",
                            Price = 7800000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Топовая комплектация с технологиями премиум-класса",
                            Image = "https://wallpapers.com/images/hd/white-chevrolet-tahoe-s-u-v-profile-hxxci41yvgrn2kxs.jpg",
                            Liters = 98,
                            Name = "Chevrolet Tahoe Premier",
                            Price = 8500000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Семейный кроссовер базовой комплектации",
                            Image = "https://chevrolet.uz/assets/images/traverse/colors/2.png",
                            Liters = 85,
                            Name = "Chevrolet Traverse LS",
                            Price = 4200000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Улучшенная версия с дополнительными опциями",
                            Image = "https://chevrolet.uz/assets/images/traverse/colors/2.png",
                            Liters = 85,
                            Name = "Chevrolet Traverse LT",
                            Price = 4800000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "Премиум комплектация с полным приводом",
                            Image = "https://chevrolet.uz/assets/images/traverse/colors/2.png",
                            Liters = 85,
                            Name = "Chevrolet Traverse Premier",
                            Price = 5500000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Бизнес-седан базовой комплектации",
                            Image = "https://carforma.ru/files/images/wmarks/d7823bb0d19e6429f410250999bdee95.png",
                            Liters = 60,
                            Name = "Chevrolet Malibu LS",
                            Price = 2300000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Улучшенная версия с дополнительным оснащением",
                            Image = "https://carforma.ru/files/images/wmarks/d7823bb0d19e6429f410250999bdee95.png",
                            Liters = 60,
                            Name = "Chevrolet Malibu LT",
                            Price = 2600000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Топовая версия с премиальным интерьером",
                            Image = "https://carforma.ru/files/images/wmarks/d7823bb0d19e6429f410250999bdee95.png",
                            Liters = 60,
                            Name = "Chevrolet Malibu Premier",
                            Price = 3000000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Компактный кроссовер базовой версии",
                            Image = "https://выхлоп43.рф/assets/cache_image/resources/404/shevrolet-captiva_500x0_82c.png",
                            Liters = 70,
                            Name = "Chevrolet Captiva LS",
                            Price = 2800000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Средняя комплектация с полным приводом",
                            Image = "https://выхлоп43.рф/assets/cache_image/resources/404/shevrolet-captiva_500x0_82c.png",
                            Liters = 70,
                            Name = "Chevrolet Captiva LT",
                            Price = 3200000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Description = "Топовая версия с расширенными возможностями",
                            Image = "https://выхлоп43.рф/assets/cache_image/resources/404/shevrolet-captiva_500x0_82c.png",
                            Liters = 70,
                            Name = "Chevrolet Captiva Premier",
                            Price = 3600000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "Семейный минивэн базовой комплектации",
                            Image = "https://storage.yandexcloud.net/cdn.carso.ru/uploads/new_car/175/colors/image_634.png",
                            Liters = 65,
                            Name = "Chevrolet Orlando LS",
                            Price = 2100000m,
                            Spaces = 7,
                            Transmission = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Автоматическая коробка, улучшенный комфорт",
                            Image = "https://storage.yandexcloud.net/cdn.carso.ru/uploads/new_car/175/colors/image_634.png",
                            Liters = 65,
                            Name = "Chevrolet Orlando LT",
                            Price = 2400000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Премиум версия с мультимедийным комплексом",
                            Image = "https://storage.yandexcloud.net/cdn.carso.ru/uploads/new_car/175/colors/image_634.png",
                            Liters = 65,
                            Name = "Chevrolet Orlando Premier",
                            Price = 2800000m,
                            Spaces = 7,
                            Transmission = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Description = "Спортивное купе с двигателем V6",
                            Image = "https://pngicon.ru/file/uploads/avto_camaro.png",
                            Liters = 120,
                            Name = "Chevrolet Camaro LT",
                            Price = 5500000m,
                            Spaces = 4,
                            Transmission = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Мощная версия с двигателем V8",
                            Image = "https://pngicon.ru/file/uploads/avto_camaro.png",
                            Liters = 150,
                            Name = "Chevrolet Camaro SS",
                            Price = 6800000m,
                            Spaces = 4,
                            Transmission = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Топовая спортивная версия с суперчарджером",
                            Image = "https://pngicon.ru/file/uploads/avto_camaro.png",
                            Liters = 180,
                            Name = "Chevrolet Camaro ZL1",
                            Price = 8200000m,
                            Spaces = 4,
                            Transmission = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Стильный кроссовер базовой комплектации",
                            Image = "https://di-uploads-pod2.dealerinspire.com/bobsteelechevy/uploads/2022/06/mlp-img-top-2022-blazer.png",
                            Liters = 90,
                            Name = "Chevrolet Blazer LS",
                            Price = 3900000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Description = "Спортивная версия с улучшенными характеристиками",
                            Image = "https://di-uploads-pod2.dealerinspire.com/bobsteelechevy/uploads/2022/06/mlp-img-top-2022-blazer.png",
                            Liters = 90,
                            Name = "Chevrolet Blazer RS",
                            Price = 4500000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Description = "Топовая комплектация с полным пакетом опций",
                            Image = "https://di-uploads-pod2.dealerinspire.com/bobsteelechevy/uploads/2022/06/mlp-img-top-2022-blazer.png",
                            Liters = 90,
                            Name = "Chevrolet Blazer Premier",
                            Price = 5200000m,
                            Spaces = 5,
                            Transmission = 1,
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
