import React from 'react';

export const AllReviews = [
    { id: 1, carId: 1, name: 'Alex', post: 'Mechanic', photo: '/images/man.jpg', reviewText: 'Nice car!', date: '21.05.2025' },
    { id: 2, carId: 1, name: 'Emma', post: 'Designer', photo: '/images/woman.jpg', reviewText: 'Great design, but the engine is a bit noisy.', date: '15.03.2023' },
    { id: 3, carId: 2, name: 'Michael', post: 'Engineer', photo: '/images/man.jpg', reviewText: 'Very comfortable ride.', date: '10.07.2022' },
    { id: 4, carId: 2, name: 'Sophia', post: 'Teacher', photo: '/images/woman.jpg', reviewText: 'Not happy with the fuel consumption.', date: '05.11.2021' },
    { id: 5, carId: 3, name: 'James', post: 'Doctor', photo: '/images/man.jpg', reviewText: 'Excellent handling on the road.', date: '20.09.2024' },
    { id: 6, carId: 3, name: 'Olivia', post: 'Nurse', photo: '/images/woman.jpg', reviewText: 'The interior could be more spacious.', date: '12.04.2020' },
    { id: 7, carId: 4, name: 'William', post: 'Lawyer', photo: '/images/man.jpg', reviewText: 'Very reliable car.', date: '08.06.2023' },
    { id: 8, carId: 4, name: 'Ava', post: 'Artist', photo: '/images/woman.jpg', reviewText: 'The paint quality is not up to the mark.', date: '25.12.2022' },
    { id: 9, carId: 5, name: 'Benjamin', post: 'Chef', photo: '/images/man.jpg', reviewText: 'Amazing acceleration!', date: '17.08.2021' },
    { id: 10, carId: 5, name: 'Mia', post: 'Writer', photo: '/images/woman.jpg', reviewText: 'The brakes are not very responsive.', date: '03.02.2025' },
    { id: 11, carId: 6, name: 'Lucas', post: 'Architect', photo: '/images/man.jpg', reviewText: 'Beautiful exterior design.', date: '22.10.2024' },
    { id: 12, carId: 6, name: 'Charlotte', post: 'Photographer', photo: '/images/woman.jpg', reviewText: 'The infotainment system is outdated.', date: '14.05.2020' },
    { id: 13, carId: 7, name: 'Henry', post: 'Scientist', photo: '/images/man.jpg', reviewText: 'Very efficient on fuel.', date: '09.03.2023' },
    { id: 14, carId: 7, name: 'Amelia', post: 'Musician', photo: '/images/woman.jpg', reviewText: 'The seats are not very comfortable.', date: '30.11.2022' },
    { id: 15, carId: 8, name: 'Theodore', post: 'Pilot', photo: '/images/man.jpg', reviewText: 'Great safety features.', date: '11.07.2021' },
    { id: 16, carId: 8, name: 'Harper', post: 'Journalist', photo: '/images/woman.jpg', reviewText: 'The suspension is too stiff.', date: '04.01.2025' },
    { id: 17, carId: 9, name: 'Jack', post: 'Entrepreneur', photo: '/images/man.jpg', reviewText: 'Very spacious interior.', date: '19.09.2024' },
    { id: 18, carId: 9, name: 'Evelyn', post: 'Dancer', photo: '/images/woman.jpg', reviewText: 'The engine is not powerful enough.', date: '13.04.2020' },
    { id: 19, carId: 10, name: 'Oliver', post: 'Developer', photo: '/images/man.jpg', reviewText: 'Excellent build quality.', date: '07.06.2023' },
    { id: 20, carId: 10, name: 'Grace', post: 'Designer', photo: '/images/woman.jpg', reviewText: 'The headlights are not bright enough.', date: '24.12.2022' },
    { id: 21, carId: 11, name: 'Leo', post: 'Artist', photo: '/images/man.jpg', reviewText: 'Very smooth ride.', date: '16.08.2021' },
    { id: 22, carId: 11, name: 'Victoria', post: 'Teacher', photo: '/images/woman.jpg', reviewText: 'The tires wear out quickly.', date: '02.02.2025' },
    { id: 23, carId: 12, name: 'Samuel', post: 'Engineer', photo: '/images/man.jpg', reviewText: 'Great value for money.', date: '21.10.2024' },
    { id: 24, carId: 12, name: 'Scarlett', post: 'Nurse', photo: '/images/woman.jpg', reviewText: 'The air conditioning is weak.', date: '14.05.2020' },
    { id: 25, carId: 13, name: 'Daniel', post: 'Doctor', photo: '/images/man.jpg', reviewText: 'Very comfortable seats.', date: '09.03.2023' },
    { id: 26, carId: 13, name: 'Aria', post: 'Writer', photo: '/images/woman.jpg', reviewText: 'The steering is too light.', date: '30.11.2022' },
    { id: 27, carId: 14, name: 'Elijah', post: 'Lawyer', photo: '/images/man.jpg', reviewText: 'Excellent fuel efficiency.', date: '11.07.2021' },
    { id: 28, carId: 14, name: 'Luna', post: 'Artist', photo: '/images/woman.jpg', reviewText: 'The paint is prone to scratches.', date: '04.01.2025' },
    { id: 29, carId: 15, name: 'Matthew', post: 'Chef', photo: '/images/man.jpg', reviewText: 'Very reliable car.', date: '19.09.2024' },
    { id: 30, carId: 15, name: 'Chloe', post: 'Photographer', photo: '/images/woman.jpg', reviewText: 'The interior is not very modern.', date: '13.04.2020' },
    { id: 31, carId: 16, name: 'Joseph', post: 'Scientist', photo: '/images/man.jpg', reviewText: 'Great handling on the road.', date: '07.06.2023' },
    { id: 32, carId: 16, name: 'Penelope', post: 'Musician', photo: '/images/woman.jpg', reviewText: 'The engine is a bit noisy.', date: '24.12.2022' },
    { id: 33, carId: 17, name: 'David', post: 'Pilot', photo: '/images/man.jpg', reviewText: 'Very comfortable ride.', date: '16.08.2021' },
    { id: 34, carId: 17, name: 'Lily', post: 'Journalist', photo: '/images/woman.jpg', reviewText: 'The fuel consumption is high.', date: '02.02.2025' },
    { id: 35, carId: 18, name: 'John', post: 'Entrepreneur', photo: '/images/man.jpg', reviewText: 'Excellent build quality.', date: '21.10.2024' },
    { id: 36, carId: 18, name: 'Zoey', post: 'Dancer', photo: '/images/woman.jpg', reviewText: 'The headlights are not bright enough.', date: '14.05.2020' },
    { id: 37, carId: 19, name: 'Thomas', post: 'Developer', photo: '/images/man.jpg', reviewText: 'Very spacious interior.', date: '09.03.2023' },
    { id: 38, carId: 19, name: 'Ella', post: 'Designer', photo: '/images/woman.jpg', reviewText: 'The tires wear out quickly.', date: '30.11.2022' },
    { id: 39, carId: 20, name: 'Christopher', post: 'Artist', photo: '/images/man.jpg', reviewText: 'Great value for money.', date: '11.07.2021' },
    { id: 40, carId: 20, name: 'Avery', post: 'Teacher', photo: '/images/woman.jpg', reviewText: 'The air conditioning is weak.', date: '04.01.2025' },
    { id: 41, carId: 21, name: 'Andrew', post: 'Engineer', photo: '/images/man.jpg', reviewText: 'Very comfortable seats.', date: '19.09.2024' },
    { id: 42, carId: 21, name: 'Sofia', post: 'Nurse', photo: '/images/woman.jpg', reviewText: 'The steering is too light.', date: '13.04.2020' },
    { id: 43, carId: 22, name: 'Joshua', post: 'Doctor', photo: '/images/man.jpg', reviewText: 'Excellent fuel efficiency.', date: '07.06.2023' },
    { id: 44, carId: 22, name: 'Riley', post: 'Writer', photo: '/images/woman.jpg', reviewText: 'The paint is prone to scratches.', date: '24.12.2022' },
    { id: 45, carId: 23, name: 'Gabriel', post: 'Lawyer', photo: '/images/man.jpg', reviewText: 'Very reliable car.', date: '16.08.2021' },
    { id: 46, carId: 23, name: 'Hannah', post: 'Artist', photo: '/images/woman.jpg', reviewText: 'The interior is not very modern.', date: '02.02.2025' },
    { id: 47, carId: 24, name: 'Anthony', post: 'Chef', photo: '/images/man.jpg', reviewText: 'Great handling on the road.', date: '21.10.2024' },
    { id: 48, carId: 24, name: 'Layla', post: 'Photographer', photo: '/images/woman.jpg', reviewText: 'The engine is a bit noisy.', date: '14.05.2020' },
    { id: 49, carId: 25, name: 'Dylan', post: 'Scientist', photo: '/images/man.jpg', reviewText: 'Very comfortable ride.', date: '09.03.2023' },
    { id: 50, carId: 25, name: 'Zoe', post: 'Musician', photo: '/images/woman.jpg', reviewText: 'The fuel consumption is high.', date: '30.11.2022' },
    { id: 51, carId: 26, name: 'Isaac', post: 'Pilot', photo: '/images/man.jpg', reviewText: 'Excellent build quality.', date: '11.07.2021' },
    { id: 52, carId: 26, name: 'Stella', post: 'Journalist', photo: '/images/woman.jpg', reviewText: 'The headlights are not bright enough.', date: '04.01.2025' },
    { id: 53, carId: 27, name: 'Ethan', post: 'Entrepreneur', photo: '/images/man.jpg', reviewText: 'Very spacious interior.', date: '19.09.2024' },
    { id: 54, carId: 27, name: 'Hazel', post: 'Dancer', photo: '/images/woman.jpg', reviewText: 'The tires wear out quickly.', date: '13.04.2020' },
    { id: 55, carId: 28, name: 'James', post: 'Developer', photo: '/images/man.jpg', reviewText: 'Great value for money.', date: '07.06.2023' },
    { id: 56, carId: 28, name: 'Aurora', post: 'Designer', photo: '/images/woman.jpg', reviewText: 'The air conditioning is weak.', date: '24.12.2022' },
    { id: 57, carId: 29, name: 'Logan', post: 'Artist', photo: '/images/man.jpg', reviewText: 'Very comfortable seats.', date: '16.08.2021' },
    { id: 58, carId: 29, name: 'Quinn', post: 'Teacher', photo: '/images/woman.jpg', reviewText: 'The steering is too light.', date: '02.02.2025' },
    { id: 59, carId: 30, name: 'Carter', post: 'Engineer', photo: '/images/man.jpg', reviewText: 'Excellent fuel efficiency.', date: '21.10.2024' },
    { id: 60, carId: 30, name: 'Clara', post: 'Nurse', photo: '/images/woman.jpg', reviewText: 'The paint is prone to scratches.', date: '14.05.2020' }
];
